-- Tạo role 
CREATE ROLE ROLE_BENHNHAN;
CREATE ROLE ROLE_NHANVIEN; 
CREATE ROLE ROLE_YBSI; 
CREATE ROLE ROLE_CSYT; 
CREATE ROLE ROLE_THANHTRA; 
CREATE ROLE ROLE_NGHIENCUU; 

--Phân quyền cho role ROLE_NHANVIEN
GRANT SELECT, UPDATE ON NHANVIEN TO ROLE_NHANVIEN;
GRANT CREATE SESSION TO ROLE_NHANVIEN;

--Phân quyền cho role ROLE_THANHTRA
GRANT SELECT ON HSBA TO ROLE_THANHTRA;
GRANT SELECT ON HSBA_DV TO ROLE_THANHTRA;
GRANT SELECT ON NHANVIEN TO ROLE_THANHTRA;
GRANT SELECT ON BENHNHAN TO ROLE_THANHTRA;
GRANT SELECT ON CSYT TO ROLE_THANHTRA;
GRANT CREATE SESSION TO ROLE_THANHTRA;

--Phân quyền cho role ROLE_CSYT 
GRANT SELECT, UPDATE, INSERT ON HSBA TO ROLE_CSYT;
GRANT SELECT, UPDATE, INSERT ON HSBA_DV TO ROLE_CSYT;
GRANT CREATE SESSION TO ROLE_CSYT;

--Phân quyền cho role ROLE_BENHNHAN
GRANT SELECT, UPDATE ON BENHNHAN TO ROLE_BENHNHAN;
GRANT CREATE SESSION TO ROLE_BENHNHAN;

--Phân quyền cho role ROLE_YBSI
GRANT SELECT ON HSBA TO ROLE_YBSI;
GRANT SELECT ON HSBA_DV TO ROLE_YBSI;
GRANT SELECT ON BENHNHAN TO ROLE_YBSI;
GRANT CREATE SESSION TO ROLE_YBSI;

--Phân quyền cho role ROLE_NGHIENCUU
GRANT SELECT ON HSBA TO ROLE_NGHIENCUU;
GRANT SELECT ON HSBA_DV TO ROLE_NGHIENCUU;


