-- gán role ROLE_THANHTRA cho nhân viên có vai trò thanh tra
GRANT ROLE_THANHTRA TO NV501 ; 
GRANT ROLE_THANHTRA TO NV502 ; 
GRANT ROLE_THANHTRA TO NV503 ; 
GRANT ROLE_THANHTRA TO NV504 ; 
GRANT ROLE_THANHTRA TO NV505 ; 
GRANT ROLE_THANHTRA TO NV506 ; 
