alter session set "_ORACLE_SCRIPT"=true;
CREATE USER QTV IDENTIFIED BY quantrivien;
GRANT DBA TO QTV;
GRANT CREATE SESSION TO QTV;
GRANT CREATE ANY CONTEXT, CREATE PROCEDURE TO QTV;
GRANT EXECUTE ON DBMS_SESSION TO QTV;
--?? c� th? truy c?p DBA_ROLE_PRIVS trong function
GRANT SELECT ANY DICTIONARY TO QTV; 
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO QTV;
GRANT ALTER SESSION TO QTV;
