CREATE TABLE HSBA
(
MAHSBA CHAR(7) PRIMARY KEY,
MABN CHAR(7),
NGAY DATE,
CHUANDOAN VARCHAR(50),
MABS CHAR(7),
MAKHOA CHAR(7),
MACSYT CHAR(7),
KETLUAN VARCHAR(50)
);



CREATE TABLE HSBA_DV
(
MAHSBA CHAR(7),
MADV CHAR(7),
NGAY DATE,
MAKTV CHAR(7),
KETQUA VARCHAR(50),
PRIMARY KEY (MAHSBA,MADV,NGAY)
);

/

CREATE TABLE BENHNHAN 
(
MABN CHAR(7) PRIMARY KEY,
MACSYT CHAR(7),
TENBN VARCHAR2(50),
CMND CHAR(11),
NGAYSINH DATE,
SONHA INT,
TENDUONG VARCHAR2(50),
QUANHUYEN VARCHAR2(50),
TINHTP VARCHAR2(50),
TIENSUBENH VARCHAR2(50),
TIENSUBENHGD VARCHAR2(50),
DIUNGTHUOC VARCHAR2(50)
);

/

CREATE TABLE CSYT
(
MACSYT CHAR(7)PRIMARY KEY,
TENCSYT VARCHAR2(50),
DCCSYT VARCHAR2(50),
SDTCSYT VARCHAR2(50)
);

/


CREATE TABLE NHANVIEN
(
MANV CHAR(7) PRIMARY KEY ,
HOTEN VARCHAR2(50),
PHAI CHAR(4),
NGAYSINH DATE,
CMND CHAR(11),
QUEQUAN VARCHAR2(50),
SODT CHAR(11),
CSYT CHAR(7),
VAITRO VARCHAR2(10),
CHUYENKHOA VARCHAR2(20)
);
/

ALTER TABLE HSBA ADD CONSTRAINT FK_MABN FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN);

ALTER TABLE HSBA ADD CONSTRAINT FK_MABS FOREIGN KEY (MABS) REFERENCES NHANVIEN(MANV);

ALTER TABLE HSBA ADD CONSTRAINT FK_MACSYT FOREIGN KEY (MACSYT) REFERENCES CSYT(MACSYT);

--ALTER TABLE HSBA ADD CONSTRAINT FK_MAKHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);


ALTER TABLE HSBA_DV ADD CONSTRAINT FK_MAHSBV_DV FOREIGN KEY (MAHSBA) REFERENCES HSBA(MAHSBA);

--ALTER TABLE HSBA_DV ADD CONSTRAINT FK_MADV FOREIGN KEY (MADV) REFERENCES DICHVU(MADV);

ALTER TABLE HSBA_DV ADD CONSTRAINT FK_MAKTV FOREIGN KEY (MAKTV) REFERENCES NHANVIEN(MANV);

ALTER TABLE BENHNHAN ADD CONSTRAINT FK_MACSYT_BN FOREIGN KEY (MACSYT) REFERENCES CSYT(MACSYT);

ALTER TABLE NHANVIEN ADD CONSTRAINT FK_MACSYT_NV FOREIGN KEY (CSYT) REFERENCES CSYT(MACSYT);




--Xem dach sách tất cả người dùng trong hệ thống

SELECT * FROM Dba_users;



-- XEM  THÔNG TIN VỀ QUYỀN CỦA MỖI USER/ ROLE TRÊN CSDL

SELECT * FROM Dba_sys_privs;

SELECT * FROM Dba_tab_privs;



-- THÊM MỚI ROLE
CREATE OR REPLACE PROCEDURE ADD_ROLE 
(ROLE_NAME  IN CHAR)
IS
BEGIN

END;
